### ISSUE TITLE
Failed to extract Bundle ID and version, are you supplying a valid IPA-file?

### ISSUE THREAD

**Issue by KamilGawelek1** [simonnilsson/ios-uploader#15] opened 2021-06-11 20:37 UTC
Hi I have issues like in #14 and I dont know where I can accept this payment agreement anyone can help me?

**Comment by simonnilsson** [comment] 2021-06-12 09:37
Hi. I don't think the agreement not being accepted is the actual issue. This error occurs while reading the IPA file, before any actual contact has been made to Apple servers. But in order to identify the real cause I would need a IPA file to troubleshoot with.

Anyone willing to supply one can send a link to: simonnilsson@altmails.com

**Comment by simonnilsson** [comment] 2021-06-27 17:16
Thanks to Émeric for sending a IPA file. This IPA gave an error during unpacking with the **unzipper** module. 

`Error: invalid signature`

Not sure what the cause of this is but using a different module called **yauzl** it worked fine. I rewrote the code to use this module instead, hopefully this should solve issues seen by other people as well.  The application can now also give a couple different error messages depending on what step of bundle info extraction fails.

For anyone having this issue, please update to **v1.4.0**. Will close this issue for now.

**Closed as completed by simonnilsson** 2021-06-27 17:16 UTC
